name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['main', 'fixtures/**']

jobs:
  yamllint:
    name: YAML lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: parsable
          config_file: .yamllint.yml

  markdownlint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            **/*.md
            !node_modules/**

  tests:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install project and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . pytest

      - name: Sanity check — validate sample fixture
        run: |
          labki-validate validate tests/fixtures/basic_repo/manifest.yml schema/v1_0_0/manifest.schema.json

      - name: Run test suite
        run: pytest -q
