name: lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install ruff and black
        run: pip install ruff black
      - name: Black formatting
        run: black --check .
      - name: Ruff linting
        run: ruff check